Mihara/RasterPropMonitor

MechJebRPM/MechJebRPM.cs, MechJebRPM/MechJebRPMButtons.cs, RasterPropMonitor/Core/PropMonitorComputer.cs, RasterPropMonitor/Core/RasterPropMonitor.cs, RasterPropMonitor/Handlers/JSIInternalRPMButtons.cs, RasterPropMonitor/Handlers/JSIOrbitDisplay.cs, RasterPropMonitor/Handlers/JSIPrimaryFlightDisplay.cs
Fixes issue #141 - I don't know that part.uid == part.GetHashCode(), but at the least it compiles, and presumably GetHashCode generates a unique ID.
=> Proposed fix for KSP 0.90

BumpBuildNumber/BumpBuildNumber.csproj, FormatterTests/FormatterTests.csproj, GameData/JSI/RPMPodPatches/BasicMFD/p5_crew40x20.txt, MechJebRPM/MechJebRPM.csproj, RasterPropMonitor.sln, RasterPropMonitor/Core/PropMonitorComputer.cs, RasterPropMonitor/RasterPropMonitor.csproj, SharedAssemblyInfo.cs
Add the SASMODE* variables (Issue #143), fix for TGTREL* (Issue #145), add crew TITLE, LEVEL, and EXPERIENCE fields, plus update the crew page of the basic MFD (Issue #146).  Bump the assembly and release versions everywhere to 0.19.0
=> Add new variables (SASMODE, crew experience stuff), Bump version 0.19.0

RasterPropMonitor/Handlers/JSIInternalRPMButtons.cs
Adds setter / query methods for JSIInternalRPMButtons.  Finishes
implementing Issue #143
=> Add SAS mode control callbacks

GameData/JSI/RasterPropMonitor/RasterPropMonitor.version, RasterPropMonitor/Core/CustomVariable.cs, RasterPropMonitor/Core/PropMonitorComputer.cs, RasterPropMonitor/Handlers/JSIInternalRPMButtons.cs, RasterPropMonitor/RasterPropMonitor.csproj
Addresses issue #150, and indirectly addresses issue #131.
=> Add support for user-defined custom variables

RasterPropMonitor/Core/SIFormatter.cs, RasterPropMonitor/Handlers/JSITargetMenu.cs
And stop allowing micro- and milli- SI formats through the SIP formatted - they're a bit silly (reporting millimeter / micrometer distances and velocities).
=> Add Target Menu support for arming/disarming grapple nodes

GameData/JSI/RPMPodPatches/PatchesStock/mk2-spp-cockpits.cfg, RasterPropMonitor/Core/CelestialBodyExtensions.cs, RasterPropMonitor/Core/PropMonitorComputer.cs, RasterPropMonitor/Core/SIFormatter.cs, RasterPropMonitor/Handlers/JSIHeadsUpDisplay.cs, RasterPropMonitor/Handlers/JSIOrbitDisplay.cs
Fixes Issue #166 and #161, and adds SPP cockpit RPM overrides from nli2work #160
=> KSP 1.0 compatibility fixes

RasterPropMonitor/Auxiliary modules/JSIInternalEVAHatch.cs, RasterPropMonitor/Core/PropMonitorComputer.cs
Plus tweaks, and a fix to the EVA hatch.
=> New Variables

FAQ.md, RasterPropMonitor/Core/PropMonitorComputer.cs, RasterPropMonitor/Core/UtilityFunctions.cs, RasterPropMonitor/Handlers/JSIPrimaryFlightDisplay.cs
=> More v0.19.3 feature implementations

RasterPropMonitor/Core/PropMonitorComputer.cs, RasterPropMonitor/Handlers/JSIPrimaryFlightDisplay.cs
It doesn't work, and I don't have a save here that I can test with, so I'll disable it until I can get to it.
=> More v0.19.3 variables, and turn off waypoints

GameData/JSI/RPMPodPatches/PatchesStock/mk1-inline-patch.cfg, GameData/JSI/RPMPodPatches/PatchesStock/mk1-inline-remade-internal.cfg, GameData/JSI/RPMPodPatches/PatchesStock/mk3cockpit-patch.cfg, RasterPropMonitor/Auxiliary modules/JSIVariableAnimator.cs, RasterPropMonitor/Core/UtilityFunctions.cs, RasterPropMonitor/Core/VariableOrNumber.cs, RasterPropMonitor/Handlers/JSIGraphingBackground.cs
So I can get a dev build out and exposed while I'm unable to work on RPM this week.
=> Last batch of v0.19.4 changes for a couple of days

MechJebRPM/MechJebRPM.csproj, RasterPropMonitor.sln, RasterPropMonitor/Auxiliary modules/JSIActionGroupSwitch.cs, RasterPropMonitor/Auxiliary modules/JSITransparentPod.cs, RasterPropMonitor/Core/PropMonitorComputer.cs, RasterPropMonitor/Handlers/JSIGraphingBackground.cs, RasterPropMonitor/RasterPropMonitor.csproj, SharedAssemblyInfo.cs
=> Last? round of v0.20.0 features

GameData/JSI/RPMPodPatches/BasicMFD/p1_landing40x20.txt, GameData/JSI/RPMPodPatches/BasicMFD/p3_target40x20.txt
Some pages still referenced variables in old format.
=> change some variables in MFD pages to SYSR_ convention

RasterPropMonitor/Core/PropMonitorComputer.cs
Just a simple variable I wanted. I didn't compile and test this, but honestly if I messed up a simple +=1 and switch statement, I should probably go cry in a corner for a bit.
Which means I probably messed something up somewhere.
=> Added variable for number of experiments stored onboard.

GameData/JSI/RasterPropMonitor/RasterPropMonitor.version, RasterPropMonitor/Auxiliary modules/JSIVariableAnimator.cs, RasterPropMonitor/Core/MonitorPage.cs, RasterPropMonitor/Core/PropMonitorComputer.cs, RasterPropMonitor/Core/RasterPropMonitor.cs, RasterPropMonitor/Core/TextRenderer.cs, RasterPropMonitor/Core/UtilityFunctions.cs, RasterPropMonitor/Handlers/IJSIModule.cs, RasterPropMonitor/Handlers/JSIHeadsUpDisplay.cs, RasterPropMonitor/Handlers/JSIPrimaryFlightDisplay.cs, RasterPropMonitor/RasterPropMonitor.csproj, RasterPropMonitor/Shaders/RPM-DisplayShader-compiled.shader, RasterPropMonitor/Shaders/RPM-DisplayShader.shader, RasterPropMonitor/Shaders/RPM-FontShader-compiled.shader, RasterPropMonitor/Shaders/RPM-FontShader.shader, RasterPropMonitor/Shaders/makeshaders.bat
Fix some text renderer issues, a bug in the IJSIModule design, and some other odds & ends.
=> Another v0.21.0 update

FAQ.md, GameData/JSI/RPMPodPatches/BasicMFD/pa_HUDPFD.txt, GameData/JSI/RasterPropMonitor/RasterPropMonitor.version, RasterPropMonitor.sln, RasterPropMonitor/Auxiliary modules/JSIActionGroupSwitch.cs, RasterPropMonitor/Auxiliary modules/JSIInternalBackgroundNoise.cs, RasterPropMonitor/Auxiliary modules/JSIPropTextureShift.cs, RasterPropMonitor/Auxiliary modules/JSIVariableAnimator.cs, RasterPropMonitor/Auxiliary modules/JSIVariableLabel.cs, RasterPropMonitor/Core/PropMonitorComputer.cs, RasterPropMonitor/Core/RasterPropMonitor.cs, RasterPropMonitor/Core/UtilityFunctions.cs, RasterPropMonitor/Handlers/JSIGimbal.cs, RasterPropMonitor/Handlers/JSIHeadsUpDisplay.cs, RasterPropMonitor/Handlers/JSIInternalRPMButtons.cs, RasterPropMonitor/Handlers/JSIParachute.cs, RasterPropMonitor/Handlers/JSIPrimaryFlightDisplay.cs, RasterPropMonitor/RasterPropMonitor.csproj, RasterPropMonitor/Shaders/RPM-CroppedDisplayShader-compiled.shader, RasterPropMonitor/Shaders/RPM-CroppedDisplayShader.shader, RasterPropMonitor/Shaders/makeshaders.bat, SharedAssemblyInfo.cs
Bugfixes, mostly, and a little bit of refactoring.
=> Changes for v0.21.2

GameData/JSI/RPMPodPatches/BasicMFD/MFD40x20.cfg
SCANsat v14.2 has a few additional RPM display functions.
The values in this config are all the same as the default values for SCANsatRPM, so they aren't technically needed. But I would like to have everything in the config in case anyone wants to change something or use it as a template.
=> Minor update for SCANsat v14.2 MFD config

RasterPropMonitor/Auxiliary modules/JSIRadar.cs, RasterPropMonitor/Auxiliary modules/JSISwitchableVariableLabel.cs, RasterPropMonitor/Core/RPMVCEvaluators.cs, RasterPropMonitor/Core/RPMVCVariableToObject.cs, RasterPropMonitor/Core/RPMVesselComputer.cs, RasterPropMonitor/Core/StringProcessor.cs, RasterPropMonitor/Handlers/IJSIModule.cs, RasterPropMonitor/Handlers/JSIInternalRPMButtons.cs, RasterPropMonitor/Handlers/JSIKAC.cs, RasterPropMonitor/Handlers/JSIMechJeb.cs, RasterPropMonitor/Handlers/KACWrapper.cs, RasterPropMonitor/RasterPropMonitor.csproj
JSIRadar, JSIKAC (Kerbal Alarm Clock), MechJeb spaceplane guidance...
=> More v0.23.0 features

RasterPropMonitor/Auxiliary modules/JSIRadar.cs, RasterPropMonitor/Auxiliary modules/JSITransparentPod.cs, RasterPropMonitor/Core/RPMVCEvaluators.cs, RasterPropMonitor/Core/RPMVCVariableToObject.cs, RasterPropMonitor/Core/RPMVesselComputer.cs, RasterPropMonitor/Core/UtilityFunctions.cs, RasterPropMonitor/Handlers/JSIFAR.cs, RasterPropMonitor/Handlers/JSIMechJeb.cs
New Variables, new plugin methods, fixes, etc.
=> v0.23.0 refresh

RasterPropMonitor/Auxiliary modules/JSITransparentPod.cs
Moved the portrait cams checking out of OnUpdate to be only fired on
GameEvents where crew board/EVA or transfer.
=> JSITransparentPods slight performance improvement

RasterPropMonitor/Auxiliary modules/JSITransparentPod.cs
Fixed camera portraits not updating correctly and showing Crew from other vessels in range.
Added performance enhancement for all loaded vessels. If they are NOT the currently active vessel they will automatically turn off Transparency setting when they are more than distanceToCameraThreshold away from the flight camera. 
distanceToCameraThreshold is default set to 100m but can be changed by specifying another value for this var via the JSITransparentPod module settings per internal part.
=> JSITransparentPod - fix portrait cams bug and more performance.

RasterPropMonitor/Auxiliary modules/JSITransparentPod.cs
Fix the portrait stats, a bug was occurring where it seems
vessel.isActiveVessel and kerbalref.InVessel do not correlate correctly
to the active vessel? Changed it to compare the actual Vessel GUID.
=> JSITransparentPod - Portrait cameras fixed once and for all?

.gitignore, RasterPropMonitor/Core/AeroExtensions.cs, RasterPropMonitor/Core/RPMVCVariableToObject.cs, RasterPropMonitor/Core/RPMVesselComputer.cs
=> Fixes for v0.25.0

RasterPropMonitor/Core/MathVariable.cs
Allows for squaring and rooting.
This is the first time i've done something like this so you may want to double check it.
=> Add Power operator to math variables

RasterPropMonitor/Core/MathVariable.cs
Added angle delta which gives the difference between angles.
Also added Atan2 with gives you the angle between 2 coordinates.
Let me know what you think!
=> Add more operators to math variables

FAQ.md, GameData/JSI/RPMPodPatches/BasicMFD/MFD40x20.cfg, RasterPropMonitor/Auxiliary modules/JSIActionGroupSwitch.cs, RasterPropMonitor/Auxiliary modules/JSINumericInput.cs, RasterPropMonitor/Auxiliary modules/JSISwitch.cs, RasterPropMonitor/Auxiliary modules/JSISwitchableVariableLabel.cs, RasterPropMonitor/Auxiliary modules/JSIVariableAnimator.cs, RasterPropMonitor/Auxiliary modules/JSIVariableLabel.cs, RasterPropMonitor/Core/MonitorPage.cs, RasterPropMonitor/Core/PropMonitorComputer.cs, RasterPropMonitor/Core/RPMVCPersistence.cs, RasterPropMonitor/Core/RPMVCVariableToObject.cs, RasterPropMonitor/Core/RPMVesselComputer.cs, RasterPropMonitor/Core/RasterPropMonitor.cs, RasterPropMonitor/Core/SelectVariable.cs, RasterPropMonitor/Core/StringProcessor.cs, RasterPropMonitor/Core/UtilityFunctions.cs, RasterPropMonitor/Core/VariableHandler.cs, RasterPropMonitor/Core/VariableOrNumber.cs, RasterPropMonitor/Handlers/JSIInternalRPMButtons.cs, RasterPropMonitor/Handlers/JSIOdometer.cs, RasterPropMonitor/Handlers/JSISteerableCamera.cs, RasterPropMonitor/Handlers/JSITargetMenu.cs, RasterPropMonitor/RasterPropMonitor.csproj
Some minor fixes, some new features, some KSP 1.1 changes.
=> Another KSP 1.1 pull

RasterPropMonitor/Handlers/JSITargetMenu.cs
Fixes #498.
Okay. maybe THIS is the final v0.25.0 commit.
=> Update DPAI interface

RasterPropMonitor/Core/TextRenderer.cs
Need to look for new lines *after* we've parsed tags, or we won't handle
new lines that fall immediately after a tag.
=> Fix the derp in newline processing for ParseText

RasterPropMonitor/Core/StringProcessor.cs
Issue #506.  That was a stupid oversight....
=> Fix messed-up string format processor in the fastpath

GameData/JSI/JSIAdvTransparentPods/Plugins/Config.cfg, JSITransparentPods/JSIAdvTransparentPod.cs, JSITransparentPods/JSIAdvTransparentPods.cs, JSITransparentPods/JSIPortraits.cs, JSITransparentPods/Properties/AssemblyInfo.cs
Lots of bug fixes. Fix issues with portrait camera processing.
Fix bugs with settings file. Settings file now changed to default to
show transparent pods on all loaded parts, and fixed logic for
processing.
=> V0.1.2.0 JSIAdvTransparentPods

GameData/JSI/RPMPodPatches/PatchesStock/mk2-spp-cockpits.cfg
...by temporary disabling patch.
=> Fix overriding Mk2 Inline's internal

RasterPropMonitor/Auxiliary modules/JSIActionGroupSwitch.cs, RasterPropMonitor/Core/RPMCEvaluators.cs, RasterPropMonitor/Core/RPMVCPerModule.cs, RasterPropMonitor/Core/RPMVesselComputer.cs, RasterPropMonitor/Core/RasterPropMonitor.cs, RasterPropMonitor/Core/RasterPropMonitorComputer.cs, RasterPropMonitor/Core/UtilityFunctions.cs, RasterPropMonitor/Handlers/JSIInternalRPMButtons.cs, RasterPropMonitor/Handlers/JSIParachute.cs, RasterPropMonitor/RasterPropMonitor.csproj
=> Yet again more v0.26.1

FAQ.md
swapped square and round brackets
=> Fix the link identifiers.

RasterPropMonitor/Auxiliary modules/JSISwitchableVariableLabel.cs, RasterPropMonitor/Auxiliary modules/JSIVariableLabel.cs
Add scalars for text size. TextMeshPro needs a different scale.  Issue #592.
=> Final 1.2 push

GameData/JSI/RasterPropMonitor/RasterPropMonitor.version, README.md, RasterPropMonitor.sln, RasterPropMonitor/Core/RPMVCEvaluators.cs, RasterPropMonitor/Handlers/JSIMechJeb.cs
=> Yet another 0.28.0 beta pull

README.md
And then it's time to kick this out the door.
=> Last tweak to README

GameData/JSI/RasterPropMonitor/RasterPropMonitor.version
JSON error, and replace KSP_VERSION with KSP_VERSION_MAX
=> Tweak version file

GameData/JSI/RasterPropMonitor/Library/Parts/ExternalCameraPart/external-camera.cfg
40kg is a bit much...  Issue #661
=> Reduce the mass of the external camera

GameData/JSI/RasterPropMonitor/RasterPropMonitor.version, RasterPropMonitor.sln, RasterPropMonitor/Core/RasterPropMonitor.cs, RasterPropMonitor/Core/TextRenderer.cs, SharedAssemblyInfo.cs
Not sure why I thought it was working.  Issue #668
=> ...And D3D11
